import https from "node:https";
import http from "node:http";
import {URL} from "node:url";
import {HttpResponse,RequestOptions,VRFSApiError} from "./types";
const DEFAULT_TIMEOUT=15000;
const DEFAULT_RETRIES=2;
const DEFAULT_RETRY_DELAY=500;
const USER_AGENT="UNTITLED-VRFS-Middleware/1.0";
function sleep(ms:number,signal?:AbortSignal):Promise<void>{return new Promise((resolve,reject)=>{if(signal?.aborted){reject(new Error("Request aborted"));return;}const timer=setTimeout(resolve,ms);const onAbort=()=>{clearTimeout(timer);reject(new Error("Request aborted"));};signal?.addEventListener("abort",onAbort,{once:true});});}
function shouldRetry(status:number):boolean{return status===408||status===425||status===429||status>=500;}
function retryAfter(headers:Record<string,string|string[]|undefined>):number|null{const value=headers["retry-after"];if(!value)return null;const raw=Array.isArray(value)?value[0]:value;const seconds=Number(raw);if(Number.isFinite(seconds)&&seconds>=0)return seconds*1000;const date=Date.parse(raw);if(Number.isFinite(date))return Math.max(0,date-Date.now());return null;}
function normalizeHeaders(headers:Record<string,string|string[]|undefined>):Record<string,string|string[]|undefined>{const result:Record<string,string|string[]|undefined>={};for(const[key,value]of Object.entries(headers))result[key.toLowerCase()]=value;return result;}
function requestOnce<T>(url:string,options:RequestOptions):Promise<HttpResponse<T>>{return new Promise((resolve,reject)=>{let parsed:URL;try{parsed=new URL(url);}catch(error){reject(error);return;}const transport=parsed.protocol==="https:"?https:http;const method=options.method??"GET";const timeoutMs=options.timeoutMs??DEFAULT_TIMEOUT;const body=options.body===undefined||options.body===null?null:typeof options.body==="string"?options.body:JSON.stringify(options.body);const headers:Record<string,string>={"Accept":"application/json","User-Agent":USER_AGENT,...(options.headers??{})};if(body!==null&&!headers["Content-Length"]&&!headers["content-length"])headers["Content-Length"]=String(Buffer.byteLength(body));if(body!==null&&!headers["Content-Type"]&&!headers["content-type"])headers["Content-Type"]="application/json";const req=transport.request(parsed,{method,headers,timeout:timeoutMs},res=>{const chunks:Buffer[]=[];res.on("data",(chunk:Buffer|string)=>chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk)));res.on("end",()=>{const buffer=Buffer.concat(chunks);const text=buffer.toString("utf8");const normalized=normalizeHeaders(res.headers as Record<string,string|string[]|undefined>);let data:T|null=null;if(text.trim()){try{data=JSON.parse(text) as T;}catch{data=null;}}resolve({status:Number(res.statusCode??0),headers:normalized,data,text,url});});res.on("error",reject);});req.on("timeout",()=>req.destroy(new Error(`Request timed out after ${timeoutMs}ms`)));req.on("error",reject);const abort=()=>req.destroy(new Error("Request aborted"));if(options.signal){if(options.signal.aborted){abort();return;}options.signal.addEventListener("abort",abort,{once:true});}if(body!==null)req.write(body);req.end();});}
export async function request<T=unknown>(url:string,options:RequestOptions={}):Promise<HttpResponse<T>>{const retries=Math.max(0,options.retries??DEFAULT_RETRIES);const retryDelayMs=Math.max(0,options.retryDelayMs??DEFAULT_RETRY_DELAY);let lastError:unknown=null;for(let attempt=0;attempt<=retries;attempt++){try{const response=await requestOnce<T>(url,options);if(response.status>=200&&response.status<300)return response;if(!shouldRetry(response.status)||attempt>=retries)return response;const retryWait=retryAfter(response.headers)??retryDelayMs*Math.pow(2,attempt);await sleep(retryWait,options.signal);}catch(error){lastError=error;if(attempt>=retries)throw error;await sleep(retryDelayMs*Math.pow(2,attempt),options.signal);}}throw lastError instanceof Error?lastError:new Error("HTTP request failed");}
export async function requestJson<T=unknown>(url:string,options:RequestOptions={}):Promise<T>{const response=await request<T>(url,options);if(response.status<200||response.status>=300){const retryable=shouldRetry(response.status);throw new VRFSApiError(`HTTP ${response.status} from ${url}`,response.status,url,response.data??response.text.slice(0,1000),retryable);}if(response.data===null){if(!response.text.trim())throw new VRFSApiError("Empty response body",response.status,url,null,false);throw new VRFSApiError("Invalid JSON response",response.status,url,response.text.slice(0,1000),false);}return response.data;}
export async function getJson<T=unknown>(url:string,options:Omit<RequestOptions,"method"|"body">={}):Promise<T>{return requestJson<T>(url,{...options,method:"GET"});}
export async function postJson<T=unknown>(url:string,body:unknown,options:Omit<RequestOptions,"method"|"body">={}):Promise<T>{return requestJson<T>(url,{...options,method:"POST",body});}
export async function putJson<T=unknown>(url:string,body:unknown,options:Omit<RequestOptions,"method"|"body">={}):Promise<T>{return requestJson<T>(url,{...options,method:"PUT",body});}
export async function deleteJson<T=unknown>(url:string,options:Omit<RequestOptions,"method"|"body">={}):Promise<T>{return requestJson<T>(url,{...options,method:"DELETE"});}
export function isRetryableError(error:unknown):boolean{if(error instanceof VRFSApiError)return error.retryable;if(error instanceof Error)return /timeout|network|socket|econn|reset|aborted/i.test(error.message);return false;}
