/**
 * @module adminPanel
 * Admin panel for license management (ephemeral, owner only)
 */

import {
  ActionRowBuilder,
  ButtonBuilder,
  ButtonStyle,
  EmbedBuilder,
  ButtonInteraction,
  ChatInputCommandInteraction,
  CacheType,
} from 'discord.js';
import { getLicenseStats, listLicenseKeys } from '../database.js';
import { createKey } from '../license/keyGenerator.js';
import { formatTimestamp } from '../utils.js';
import { logger } from '../logger.js';

export class AdminPanel {
  async sendPanel(interaction: ChatInputCommandInteraction<CacheType>): Promise<void> {
    const stats = await getLicenseStats();
    const keys = await listLicenseKeys(10);

    const embed = new EmbedBuilder()
      .setColor(0x5865F2)
      .setTitle('Admin - License Management')
      .setDescription([
        'Generate and manage license keys.',
        '',
        '**Statistics**',
        `Total Keys: ${stats.total}`,
        `Used: ${stats.used}`,
        `Available: ${stats.unused}`,
        '',
        '**Recent Keys**',
        keys.length > 0 ? keys.slice(0, 5).map(k => {
          const status = k.used ? `Used by <@${k.usedBy}>` : 'Available';
          return `\`${k.key}\` - ${status}`;
        }).join('\n') : 'No keys generated yet.',
      ].join('\n'))
      .setTimestamp();

    const row = new ActionRowBuilder<ButtonBuilder>()
      .addComponents(
        new ButtonBuilder()
          .setCustomId('admin_generate_key')
          .setLabel('Generate Key')
          .setStyle(ButtonStyle.Primary),
        new ButtonBuilder()
          .setCustomId('admin_list_keys')
          .setLabel('List All Keys')
          .setStyle(ButtonStyle.Secondary),
        new ButtonBuilder()
          .setCustomId('admin_refresh')
          .setLabel('Refresh')
          .setStyle(ButtonStyle.Secondary),
      );

    await interaction.editReply({
      embeds: [embed],
      components: [row],
    });
  }

  async handleInteraction(interaction: ButtonInteraction): Promise<void> {
    const { customId } = interaction;

    if (customId === 'admin_generate_key') {
      await this.handleGenerate(interaction);
      return;
    }

    if (customId === 'admin_list_keys') {
      await this.handleList(interaction);
      return;
    }

    if (customId === 'admin_refresh') {
      await this.handleRefresh(interaction);
      return;
    }
  }

  private async handleGenerate(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });

    const key = await createKey(interaction.user.id);

    const embed = new EmbedBuilder()
      .setColor(0x00AAFF)
      .setTitle('Key Generated')
      .addFields(
        { name: 'Key', value: `\`${key}\``, inline: false },
        { name: 'Type', value: 'Single-use', inline: true },
        { name: 'Expires', value: 'Never', inline: true },
      );

    await interaction.editReply({ embeds: [embed] });

    logger.info('License key generated by admin', { 
      adminId: interaction.user.id,
      key 
    });
  }

  private async handleList(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });

    const keys = await listLicenseKeys(50);

    if (keys.length === 0) {
      await interaction.editReply({ content: 'No keys generated.' });
      return;
    }

    const embed = new EmbedBuilder()
      .setColor(0x5865F2)
      .setTitle(`Keys (${keys.length})`);

    for (const k of keys.slice(0, 20)) {
      const status = k.used 
        ? `Used by <@${k.usedBy}>` 
        : 'Available';
      
      embed.addFields({
        name: `\`${k.key}\``,
        value: `${status} | ${formatTimestamp(k.createdAt)}`,
        inline: false,
      });
    }

    if (keys.length > 20) {
      embed.setFooter({ text: `Showing 20 of ${keys.length}` });
    }

    await interaction.editReply({ embeds: [embed] });
  }

  private async handleRefresh(interaction: ButtonInteraction): Promise<void> {
    await interaction.deferReply({ ephemeral: true });
    await interaction.editReply({ content: 'Refreshed. Use /licenseadmin again to see updated panel.' });
  }
}
